[default.extend-words]
snet = "snet"
nd = "nd"
ba = "ba"
sice = "sice"
gost = "gost"

# legacy typos
hander= "hander" # ./ygglib/ipv6rwc/ipv6rwc.go:63:42

[files]
extend-exclude = [
  "*_test.go",
  "ygglib/autopeer/builtin_peers_generated.json",
]

